# Generated by Django 3.1.14 on 2022-07-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(max_length=30)),
                ('lon', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('agreement', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('paid_till', models.DateTimeField(null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('qr_code', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.storage')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
